export const characterMap = [
  "Mario",
  "Baby peach",
  "Waluigi",
  "Bowser",
  "Baby Daisy",
  "Dry bones",
  "Baby Mario",
  "Luigi",
  "Toad",
  "Donkey Kong",
  "Yoshi",
  "Wario",
  "Baby Luigi",
  "Toadette",
  "Koopa Troopa",
  "Daisy",
  "Peach",
  "Birdo",
  "Diddy Kong",
  "King boo",
  "Bowser Jr.",
  "Dry Bowser",
  "Funky Kong",
  "Rosalina",
];

export const vehicleMap = [
  "Standard Kart S",
  "Standard Kart M",
  "Standard Kart L",
  "Booster Seat",
  "Classic Dragster",
  "offroader",
  "Mini Beast",
  "Wild Wing",
  "Flame Flyer",
  "Cheep Charger",
  "Super Blooper",
  "Piranha Prowler",
  "Tiny Titan",
  "Daytripper",
  "Jetsetter",
  "Blue falcon",
  "Sprinter",
  "Honeycoupe",
  "Standard Bike S",
  "Standard Bike M",
  "Standard Bike L",
  "Bullet Bike",
  "Mach Bike",
  "Flame Runner",
  "Bit Bike",
  "Sugarscoot",
  "Wario Bike",
  "Quacker",
  "Zip Zip",
  "Shooting Star",
  "Magikruiser",
  "Sneakster",
  "Spear",
  "Jet Bubble",
  "Dolphin Dasher",
  "Phamton",
];

export const trackMap = [
  "Mario Circuit",
  "Moo Moo Meadows",
  "Mushroom Gorge",
  "Grumble Volcano",
  "Toad's Factory",
  "Coconut Mall",
  "DK Summit",
  "Wario's Gold Mine",
  "Luigi Circuit",
  "Daisy Circuit",
  "Moonview Highway",
  "Maple Treeway",
  "Bowser's Castle",
  "Rainbow Road",
  "Dry Dry Ruins",
  "Koopa Cape",
  "GCN Peach Beach",
  "GCN Mario Circuit",
  "GCN Waluigi Stadium",
  "GCN DK Mountain",
  "DS Yoshi Falls",
  "DS Desert Hills",
  "DS Peach Gardens",
  "DS Delfino Square",
  "SNES Mario Circuit 3",
  "SNES Ghost Valley 2",
  "N64 Mario Raceway",
  "N64 Sherbet Land",
  "N64 Bowser's Castle",
  "N64 DK's Jungle Parkway",
  "GBA Bowser Castle 3",
  "GBA Shy Guy Beach",
];

export const controllerMap = ["Wii Wheel", "Nunchuk", "Classic", "Gamecube"];
